name: "Chess"

on:
  issues:
    types: [opened]

jobs:
  move:
    runs-on: ubuntu-latest
    if: startsWith(github.event.issue.title, 'chess|')
    steps:

    - name: Set env vars
      run: |
        echo ::set-env name=REPOSITORY::${{ github.repository }}
        echo ::set-env name=EVENT_ISSUE_NUMBER::${{ github.event.issue.number }}
        echo ::set-env name=EVENT_USER_LOGIN::${{ github.event.issue.user.login }}
        echo ::set-env name=GITHUB_SECRET::${{ secrets.GITHUB_TOKEN }}

      # We <3 Ruby, so let's use it + Octokit to ease the
      # scripting and API interactions.

      #
      # I see your :eyes: :). This is all band-aids and stick tape.
      # Yep... I log like it's 1995 with random "puts" in places.
      #

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.1

    - name: Setup Gems
      run: |
        gem install activesupport -N --silent
        gem install octokit -N --silent
        gem install chess -N --silent

    - uses: actions/checkout@v2
    - name: Play
      run: |
        ruby ./game.rb